version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: Cardmaker
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - cardmaker
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

  api:
    build: ./api
    container_name: api
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:root@db:3306/Cardmaker"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    networks:
      - cardmaker
    expose:
      - 8000

  frontend:
    build: ./cardMakerFE
    container_name: frontend
    environment:
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - cardmaker
    expose:
      - 3000

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cardmaker
    depends_on:
      - api
      - frontend
    expose:
      - 80

volumes:
  db_data:

networks:
  cardmaker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16