services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports:
      - "3307:3307"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - cardmaker
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

  api:
    build: ./api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
      USE_API_KEY: ${USE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    networks:
      - cardmaker
    ports:
      - "8003:8003"
    healthcheck:
        test: curl --fail http://localhost:8003/tags || exit 1
        timeout: 5s
        retries: 10

  frontend:
    build: ./cardMakerFE
    environment:
      USE_API_KEY: ${USE_API_KEY}
    networks:
      - cardmaker
    ports:
      - "3005:3005"
    healthcheck:
        test: curl --fail http://localhost:3005/ || exit 1
        timeout: 5s
        retries: 10

  proxy:
    image: nginx:alpine
    ports:
      - "9875:9875"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cardmaker
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_healthy
    expose:
      - 9875

volumes:
  db_data:

networks:
  cardmaker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
