version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: Cardmaker
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - cardmaker
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 3s
      retries: 3

  server:
    build: .
    container_name: server
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:root@db:3306/Cardmaker"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - cardmaker
    expose:
      - 8000
    command: # ?? seems like depends_on (or the condition) does not work with podman - wait a few secs manually just to be sure
      - /bin/bash
      - -c
      - sleep 5 && python main.py

volumes:
  db_data:

networks:
  cardmaker: