# docker-compose -f docker-compose-dev.yml up -d --build
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports:
      - "3307:3307"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      - cardmaker
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

  api:
    build: ./api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
      API_KEY_USE: ${API_KEY_USE}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    ports:
      - "8003:8003"
    networks:
      - cardmaker
    healthcheck:
        test: curl --fail http://localhost:8000/tags || exit 1
        timeout: 5s
        retries: 10

volumes:
  db_data:

networks:
  cardmaker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16